Nublikaska
nublikaska/liquid-log pull request #3
Opened 2017-10-31 21:14 UTC by nublikaska

@ykalemi, 3 Задание.

2017-11-01 19:04 UTC, nublikaska commented
@ykalemi, пожалуйста, проверьте, ато так и не посмотрели

2017-11-02 13:34 UTC, ykalemi requested changes

2017-11-02 13:34 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +            System.setProperty("NoCsv", "yes");
К сожалению, эта ошибка слишком бросается в глаза, чтобы я не вспомнил, что видел её в другом решении. Поэтому просто копирую комментарий из другого репозитория:

System.setProperty - меняет глобальную переменную окружения. Если будет одновременно две загрузки файлов, то каждая по очереди будет менять эту глобальную переменную.

На самом деле, в этом же нет никакой необходимости - просто передайте все эти аргументы дальше в App. Смело меняйте сигнатуру и содержимое App. Метод main уже устарел и его название ничего не значит. Пусть у него будут аргументы почти такие же, как у этого контроллера - и всё станет намного проще.

2017-11-02 13:34 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +        System.setProperty("Parser", "");
Вы создаёте файл, но никак его не удаляете. Это значит, что он продолжит существовать в системе и после загрузки.

При этом, имя файла не уникальное. Т.е. если сделать одновременно две загрузки, то вторая просто удалит предыдущий файл.

Но вообще, можно обойтись без сохранения нового файла - просто передать MultipartFile дальше и потом из него сконструировать InputStream, а всё остальное останется как было.

2017-11-02 13:34 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Dparser.java
> +public class Dparser {
никак не используется?

2017-11-02 13:38 UTC, ykalemi commented
Да, у вас в коммите ещё появились файлы - sdng.log.2017-09-07 и log.txt
т.е. вы их складываете в репозиторий и теперь будете коммитить при каждом изменении. Первый файл весит 40 мегабайт, второй просто не нужен в репозитории.

Их нужно исключить из коммитов. Вы можете сказать git чтобы он их игнорировал (см. .gitignore) или просто убрать из папки проекта.

2017-11-12 11:34 UTC, closed without merging