Nublikaska
nublikaska/liquid-log pull request #5
Opened 2017-11-14 15:49 UTC by nublikaska

@ykalemi, гляньте 4 задание

2017-11-14 19:02 UTC, ykalemi requested changes

2017-11-14 19:02 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/InfluxDAO.java
> +import ru.naumen.sd40.log.parser.Implements_Interfaces.SdngParser;
имя пакета лучше без строчных букв

2017-11-14 19:02 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/InfluxDAO.java
> +    public void storeGc(BatchPoints batch, String dbName, long date, ru.naumen.sd40.log.parser.Implements_Interfaces.GCParser gc)
лучше не писать полное название класса, почему не сделать просто импорт?

2017-11-14 19:02 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +//            try (BufferedReader br = new BufferedReader(new InputStreamReader(file.getInputStream()), 32 * 1024 * 1024)) {
не оставляйте мёртвый код, это затрудняет его чтение. Для истории у вас есть git

2017-11-14 19:02 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/App.java
> +            sz = 32 * 1024 * 1024;
sz везде одинаковый - почему его сразу не вычислить?

2017-11-14 19:02 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Implements_Interfaces/Parser.java
> +public abstract class Parser implements DataParser, TimeParser {
Это оригинальное решение, но мне не очень нравится этот класс. Он парсит данные или время? Это парсер или фабрика парсеров? Кажется, он делает всё что можно - и вместо одного класса, который умеет всё, у нас появился другой.

Надо всё-таки сделать так:
- отдельные реализации TimeParser
- отдельные реализации DataParser
- никакие абстрактные классы на данном этапе не нужны
- цикл while по строкам оставьте в том же классе, где он был. Каждый парсер пусть принимает только одну строку

2017-11-15 22:13 UTC, nublikaska commented
@ykalemi, я сделал таким образом Sdng и GC, можно в метод parsing у интерфейса DataParser передавать объект TimeParser? Или я сделал не то, что вы хотели?

2017-11-16 11:28 UTC, ykalemi commented
В целом это уже почти то, что я ожидал, да. Возможно, интерфейсы несколько перегружены, я ожидал в каждом только по одному методу. Но пусть будет так.

Только дефолтный метод DataParser лучше убрать - мне кажется, что так код будет чище.

2017-11-16 11:28 UTC, ykalemi requested changes

2017-11-16 11:28 UTC, ykalemi commented on src/main/java/ru/naumen/sd40/log/parser/Interfaces/DataParser.java
> +    default void Parsing(BufferedReader br, HashMap<Long, DataParser> data, TimeParser timeParser) throws IOException, ParseException {
Дефолтный метод - это прикольно. Но я бы всё-таки предложил вернуть этот цикл в место вызова - в App. Потому что по сути здесь скрыта логика, которая к самому парсеру данных не имеет никакого отношения

2017-11-23 08:00 UTC, ykalemi approved these changes
Ок! Давайте двигаться дальше

2017-11-23 09:44 UTC, merged